<?php

/**
 * BaseStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $colors
 * @property Doctrine_Collection $Queststatus
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getColors()      Returns the current record's "colors" value
 * @method Doctrine_Collection getQueststatus() Returns the current record's "Queststatus" collection
 * @method Status              setName()        Sets the current record's "name" value
 * @method Status              setColors()      Sets the current record's "colors" value
 * @method Status              setQueststatus() Sets the current record's "Queststatus" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('colors', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Quest as Queststatus', array(
             'local' => 'id',
             'foreign' => 'status_id'));
    }
}