<?php

/**
 * BaseStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Quest $Quest
 * 
 * @method string getName()  Returns the current record's "name" value
 * @method Quest  getQuest() Returns the current record's "Quest" value
 * @method Status setName()  Sets the current record's "name" value
 * @method Status setQuest() Sets the current record's "Quest" value
 * 
 * @package    Bug Quest Tracker
 * @subpackage model
 * @author     Matthieu Mystick Derasse
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quest', array(
             'local' => 'id',
             'foreign' => 'status_id'));
    }
}