<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/04/20 22:12:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=peanut',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
