<?php

/**
 * PeanutPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    peanut
 * @subpackage model
 * @author     Alexandre pocky BALMES
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class peanutPage extends BasepeanutPage
{
}
