<?php

/**
 * Status
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Bug Quest Tracker
 * @subpackage model
 * @author     Matthieu Mystick Derasse
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Status extends BaseStatus
{
  public function __toString()
  {
    return (string) $this->getName();
  }
}
