<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/04/20 22:20:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=peanut',
  'username' => 'root',
  'password' => 't2t2d83w',
  'name' => 'doctrine',
)),);
