<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/20 22:13:00
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
