<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/05/03 22:03:27
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'backend',
      ),
    ),
  ),
);
