<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/19 23:31:35
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
