<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/05/03 00:11:41
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
