<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/23 00:43:27
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
