<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/19 23:31:38
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
