<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/05/03 00:11:36
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
