<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/05/03 00:01:25
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
