<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/04/19 22:33:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=peanut',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
